### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by KhaderMurtaja** [FACG6/Fitness#2]
####  **As a user, I can :**
  - [ ] Login to app.
  - [ ] See exercises related to current day.
  - [ ] Select days I want to do workout in.
  - [ ] Select workout exercises for each day I have selected, and modify
